<?xml version="1.0" encoding="utf-8"?><Database Name="MDH2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Z600;Initial Catalog=MDH2;User ID=chunbo1" SettingsObjectName="LoadViewDynamicly.Properties.Settings" SettingsPropertyName="MDH2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vwStudentByClass" Member="vwStudentByClasses">
    <Type Name="vwStudentByClass">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teachers" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CellPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulesHeader" Member="SchedulesHeaders">
    <Type Name="SchedulesHeader">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SchedulesHeader_SchedulesDetail" Member="SchedulesDetails" ThisKey="ID" OtherKey="HeaderId" Type="SchedulesDetail" />
    </Type>
  </Table>
  <Table Name="dbo.SchedulesDetail" Member="SchedulesDetails">
    <Type Name="SchedulesDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HeaderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SchedulesHeader_SchedulesDetail" Member="SchedulesHeader" ThisKey="HeaderId" OtherKey="ID" Type="SchedulesHeader" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vwClassAttendanceHeader" Member="vwClassAttendanceHeaders">
    <Type Name="vwClassAttendanceHeader">
      <Column Name="AttendanceHeader" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Classes" Member="Classes">
    <Type Name="Class">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Division" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dayofweek" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timeofweek" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tuition" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TeacherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TeacherCost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OfficeRentalCost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MiscCost" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CellPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StudentPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassStudents" Member="ClassStudents">
    <Type Name="ClassStudent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TuitionPaid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CasherName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CashReceived" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CheckReceived" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CheckNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreditCardReceived" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OtherReceived" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OtherSource" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vwCST" Member="vwCSTs">
    <Type Name="vwCST">
      <Column Name="Division" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dayofweek" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timeofweek" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tuition" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Teacher" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Student" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vwSemester" Member="vwSemesters">
    <Type Name="vwSemester">
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.AddSchedulesHeader" Method="AddSchedulesHeader">
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherId" Parameter="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassDate" Parameter="classDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="StartTime" Parameter="startTime" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="EndTime" Parameter="endTime" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddSchedulesDetail" Method="AddSchedulesDetail">
    <Parameter Name="HeaderId" Parameter="headerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.p_YieldCurveReport" Method="p_YieldCurveReport" IsComposable="true">
    <Parameter Name="AsOf2" Parameter="asOf2" Type="System.DateTime" DbType="DateTime" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.spDeleteSchedulesHeader" Method="spDeleteSchedulesHeader">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spClassAttendanceHeader" Method="spClassAttendanceHeader">
    <Parameter Name="ClassName" Parameter="className" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="spClassAttendanceHeaderResult">
      <Column Name="AttendanceHeader" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Semester" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetClassAttendanceDetail" Method="spGetClassAttendanceDetail">
    <Parameter Name="HeaderId" Parameter="headerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetClassAttendanceDetailResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Student" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetStudentDetail" Method="spGetStudentDetail">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetStudentDetailResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CellPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StudentPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetClassTuition" Method="spGetClassTuition">
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetClassTuitionResult">
      <Column Name="Tuition" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateCS" Method="UpdateCS">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TuitionPaid" Parameter="tuitionPaid" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="InvoiceNumber" Parameter="invoiceNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CasherName" Parameter="casherName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CashReceived" Parameter="cashReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="CheckReceived" Parameter="checkReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="CheckNumber" Parameter="checkNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CreditCardReceived" Parameter="creditCardReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="OtherReceived" Parameter="otherReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="OtherSource" Parameter="otherSource" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RegistrationDate" Parameter="registrationDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddCS" Method="AddCS">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TuitionPaid" Parameter="tuitionPaid" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="InvoiceNumber" Parameter="invoiceNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CasherName" Parameter="casherName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CashReceived" Parameter="cashReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="CheckReceived" Parameter="checkReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="CheckNumber" Parameter="checkNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CreditCardReceived" Parameter="creditCardReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="OtherReceived" Parameter="otherReceived" Type="System.Double" DbType="Float" />
    <Parameter Name="OtherSource" Parameter="otherSource" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RegistrationDate" Parameter="registrationDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteCS" Method="DeleteCS">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>